server:
  tomcat:
    uri-encoding: UTF-8
    accept-count: 100
    max-threads: 1000
    max-connections: 20000
    min-spare-threads: 10
  undertow:
      buffer-size: 512
      io-threads: 2
      worker-threads: 20

---
server:
  tomcat:
    uri-encoding: UTF-8
    #最小线程数
    min-spare-threads: 100
    #最大线程数
    max-threads: 1000
    #最大链接数
    max-connections: 10000
    #最大等待队列长度
    accept-count: 1000
    #请求头最大长度kb
    #max-http-header-size: 1048576
    #请请求体最大长度kb
    #max-http-post-size: 2097152


    